class PlanetData{
  String planetName;
  String nickName;
  String aboutDetails;
  String distanceOfSun;
  String lengthOfDay;
  String orbitalPeriod;
  String radius;
  String mass;
  String gravity;
  String surfaceArea;
  PlanetData({required this.radius,
    required this.planetName,
  required this.aboutDetails,
  required this.distanceOfSun,
  required this.gravity,
  required this.lengthOfDay,
  required this.mass,
  required this.nickName,
  required this.orbitalPeriod,
  required this.surfaceArea,});
}