class Aboutplanets {
     static const String earthabout ="Earth is the only known planet in the universe that supports life. Its unique combination of factors, including liquid water, a breathable atmosphere, and a suitable distance from the Sun, has created the ideal conditions for the development of complex organisms. Earth's magnetic field protects it from harmful solar radiation, and its atmosphere helps to regulate temperature and weather patterns";
  static const String jupiterabout = "Jupiter is the largest planet in the Solar System, a massive gas giant mostly made of hydrogen and helium. Its most famous feature is the Great Red Spot, a giant storm that has lasted for centuries. Jupiter has a strong magnetic field and dozens of moons, including Ganymede, the largest moon in the Solar System. Its powerful gravity helps shape the orbits of other objects in space.";
  static const String marsabout ="Mars is known as the “Red Planet” due to its iron-rich soil and dusty surface. It has the largest volcano and canyon in the Solar System, showing evidence of past geological activity. Mars has a thin atmosphere, mostly carbon dioxide, which makes it cold and dry. Scientists believe Mars once had liquid water, and they continue to search for signs of past or present life.";
  static const String mercuryabout = "Mercury is the smallest planet in the Solar System and the closest to the Sun. It has a rocky surface covered with craters, similar to Earth’s Moon. With no significant atmosphere to trap heat, temperatures on Mercury vary extremely between day and night. Despite being so close to the Sun, Mercury is not the hottest planet. Its rapid orbit makes a year on Mercury only 88 Earth days long.";
  static const String neptuneabout = "Neptune is the farthest planet from the Sun and is known for its deep blue color. It has strong winds and violent storms, including the Great Dark Spot, a storm similar to Jupiter’s Red Spot. Neptune is an ice giant with a composition similar to Uranus. It has faint rings and several moons, with Triton being the";
  static const String saturnabout = "Saturn is best known for its spectacular ring system, made of ice and rock particles. Like Jupiter, it is a gas giant composed mainly of hydrogen and helium. Saturn has many moons, including Titan, which has a thick atmosphere and lakes of liquid methane. Despite its large size, Saturn has a very low density and could float in water if a body of water large enough existed.";
  static const String sunabout = "The Sun is the center of the Solar System and the primary source of energy for all the planets. It is a massive ball of hot plasma, mostly hydrogen and helium, where nuclear fusion occurs, releasing light and heat. The Sun’s gravity keeps the planets in orbit, and its solar wind affects space weather throughout the system. It has an 11-year cycle of activity, producing sunspots, flares, and coronal mass ejections.";
  static const String uranusabout = "Uranus is an ice giant with a blue-green color caused by methane in its atmosphere. Unlike other planets, Uranus rotates on its side, likely due to a massive collision in its past. Its unusual tilt causes extreme seasonal changes. Uranus also has faint rings and a cold, windy atmosphere. It is one of the least explored planets in the Solar System.";
  static const String venusabout= "Venus is often called Earth’s twin because of its similar size and composition, but it has a very thick atmosphere made mostly of carbon dioxide. This causes an extreme greenhouse effect, making Venus the hottest planet in the Solar System. Its clouds of sulfuric acid also make it highly reflective. Surface conditions are so harsh that spacecraft survive only for a short time after landing.";
}
